lab_2
brstu/OTIS-2022 pull request #25
Opened 2022-10-30 23:27 UTC by Adryian4ik

2022-11-21 06:21 UTC, idzm requested changes
Запрос не должен изменять файлы в других каталогах, кроме `ii02226`.

2022-11-21 10:56 UTC, Adryian4ik commented
Добавление своих файлов

2022-12-05 06:12 UTC, idzm requested changes
Запрос должен содержать только материалы задания №2.

2022-12-12 10:11 UTC, idzm approved these changes

2022-12-12 10:12 UTC, merged