lab2
brstu/OTIS-2022 pull request #42
Opened 2022-11-04 12:06 UTC by MrsAnyki

2022-11-17 12:02 UTC, PoliNo4ka13 reviewed
Текст программы соответствует условию поставленной задачи.

2022-11-17 13:11 UTC, PoliNo4ka13 commented
Задание выполнено в соответствии с условием.

2022-11-21 06:29 UTC, idzm requested changes
Запрос не должен содержать файлы из задания №1.

2022-12-12 10:11 UTC, idzm approved these changes

2022-12-12 10:11 UTC, merged